### ISSUE TITLE
installation not working

### ISSUE THREAD

**Issue by dcxSt** [UltiRequiem/fibora#1]
Hi, I'm trying to install the binary for your crate, but it's throwing an error message... 

<img width="1550" alt="Screen Shot 2022-02-21 at 11 51 10 AM" src="https://user-images.githubusercontent.com/21654151/154997625-a95de32b-cf05-4f31-b3b7-95e6c6383eb1.png">

---

I don't think this is relevant, but I'm on ARM (the new apple w/ m1 chip)

**Comment by UltiRequiem** [comment]
Oh, thanks for the report!

Will check this 😄 

Is the same on my machine!

https://user-images.githubusercontent.com/71897736/154998498-1841bb9b-e337-4cf8-ab25-283531cc3964.mp4

**Comment by UltiRequiem** [comment]
Heeey, should be working now, thanks!
